### ISSUE TITLE
Core dump miner. It happens to all machines at the same time. So it must be in miner. Can you look at it please?

### ISSUE THREAD

**Issue by Sepkuh** [kulupu/kulupu#109]

**Comment by sgaragagghu** [comment]
[Please note 1280 pages means 2560 MB of memory will be reserved for huge pages and become not available for other usage[...].](https://xmrig.com/docs/miner/hugepages)

Since kulupu could keep in RAM two (actually I see three, for a limited amount of time) cache & datasets, you should set your OS to let you use three times 1280 pages ! So, set it to 3840 pages.

**Comment by sorpaas** [comment]
duplicate of #137
