### ISSUE TITLE
Is author inherent logic correct?

### ISSUE THREAD

**Issue by JoshOrndorff** [kulupu/kulupu#17]
The inherent to set the author contains this line

https://github.com/kulupu/kulupu/blob/3500b7f62fdf90be7608b2d813735a063ad1c458/rewards/src/lib.rs#L40

I read that as, "When attempting to set the author, ensure that some author is already set. If no author is already set, then throw the `AuthorAlreadySet` error.

That seems backward. I would expect the `ensure!` to ensure that the storage item is currently `None` meaning no author is set yet.

That being said, the node does seem to operate as expected.

**Comment by sorpaas** [comment]
Indeed this seems to be wrong. I checked and it seems that the `ensure` was added in December https://github.com/kulupu/kulupu/commit/b89009c8988ef1cf584c35266ee10b8e63fc54a5 when the spec version has already become 3. The reason why nothing yet breaks is because our current runtime spec version is still 2, so the code is unused.

I'll fix this soon.
