### ISSUE TITLE
RPC interface document

### ISSUE THREAD

**Issue by yqZhang711** [kulupu/kulupu#89]
Is there an RPC interface document? How do I get the last irreversible block? The chain_getFinalizedHead method does not get it right

**Comment by sorpaas** [comment]
> How do I get the last irreversible block? The chain_getFinalizedHead method does not get it right

There's no irreversible block in a pure PoW system like Kulupu. Finalization head will always return genesis, because no block will be finalized.

You should set your own safety threshold. For example, many ecosystem users use 120 block, which is 2 hours in the past, and treat it similar to a finalized irreversible block.
